<?php

########################################################################
# Extension Manager/Repository config file for ext: "jhe_vimeo"
#
# Auto generated by Extension Builder 2015-11-30
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Vimeo',
	'description' => 'This extension displays vimeo videos in a single or al list view',
	'category' => 'plugin',
	'author' => 'Jari-Hermann Ernst',
	'author_email' => 'jari-hermann.ernst@bad-gmbh.de',
	'author_company' => 'B·AD GmbH',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.2.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3',
			'fluid' => '1.3',
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>